Exercise.create(type_of: "chest", name: "bench press", youtube_link: "https://www.youtube.com/embed/vthMCtgVtFw", description: "description", barbell?: true, weight: 0)
Exercise.create(type_of: "chest", name: "push-ups", youtube_link: "https://www.youtube.com/embed/IODxDxX7oi4", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "chest", name: "fly", youtube_link: "https://www.youtube.com/embed/6rr5p1jCZC4", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "full body", name: "squat", youtube_link: "https://www.youtube.com/embed/aclHkVaku9U", description: "description", barbell?: true, weight: 0)
Exercise.create(type_of: "full body", name: "deadlift", youtube_link: "https://www.youtube.com/embed/8e4h2eJYNJU", description: "description", barbell?: true, weight: 0)
Exercise.create(type_of: "back", name: "seated row", youtube_link: "https://www.youtube.com/embed/A77hAjcpN1s", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "back", name: "barbell row", youtube_link: "https://www.youtube.com/embed/T3N-TO4reLQ", description: "description", barbell?: true, weight: 0)
Exercise.create(type_of: "shoulder", name: "overhead press", youtube_link: "https://www.youtube.com/embed/QAQ64hK4Xxs", description: "description", barbell?: true, weight: 0)
Exercise.create(type_of: "shoulder", name: "shrugs", youtube_link: "https://www.youtube.com/embed/0uuA5FeTZcU", description: "description", barbell?: true, weight: 0)
Exercise.create(type_of: "arm", name: "curls", youtube_link: "https://www.youtube.com/embed/QZEqB6wUPxQ", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "arm", name: "tricep extensions", youtube_link: "https://www.youtube.com/embed/PwOwL4B6iw4", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "arm", name: "pull-ups", youtube_link: "https://www.youtube.com/embed/eGo4IYlbE5g", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "leg", name: "forward lunge", youtube_link: "https://www.youtube.com/embed/QOVaHwm-Q6U", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "leg", name: "calf raises", youtube_link: "https://www.youtube.com/embed/IoZiWPV6htA", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "abs", name: "crunches", youtube_link: "https://www.youtube.com/embed/Xyd_fa5zoEU", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "abs", name: "sit-ups", youtube_link: "https://www.youtube.com/embed/1fbU_MkV7NE", description: "description", barbell?: false, weight: 0)