Exercise.create(type_of: "chest", name: "bench press", youtube_link: "", description: "description", barbell?: true, weight: 0)
Exercise.create(type_of: "chest", name: "push-ups", youtube_link: "", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "chest", name: "fly", youtube_link: "", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "full body", name: "squat", youtube_link: "", description: "description", barbell?: true, weight: 0)
Exercise.create(type_of: "full body", name: "deadlift", youtube_link: "https://www.youtube.com/embed/8e4h2eJYNJU", description: "description", barbell?: true, weight: 0)
Exercise.create(type_of: "back", name: "seated row", youtube_link: "", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "back", name: "barbell row", youtube_link: "", description: "description", barbell?: true, weight: 0)
Exercise.create(type_of: "shoulder", name: "overhead press", youtube_link: "", description: "description", barbell?: true, weight: 0)
Exercise.create(type_of: "shoulder", name: "shrugs", youtube_link: "", description: "description", barbell?: true, weight: 0)
Exercise.create(type_of: "arm", name: "curls", youtube_link: "", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "arm", name: "tricep extensions", youtube_link: "", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "arm", name: "pull-ups", youtube_link: "", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "leg", name: "forward lunge", youtube_link: "", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "leg", name: "calf raises", youtube_link: "", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "abs", name: "crunches", youtube_link: "", description: "description", barbell?: false, weight: 0)
Exercise.create(type_of: "abs", name: "sit-ups", youtube_link: "", description: "description", barbell?: false, weight: 0)